export { default as Header } from './header'
export { default as Footer } from './footer'
export { default as Intro } from './intro'
export { default as RecentWork } from './recent-work'
export { default as GetInTouch } from './get-in-touch'
export { default as Gallery } from './gallery'
export { default as Upload } from './upload'
